name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted  # prev: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run deploy
      run: make deploy-lite CC=clang
